version: '3.8'

services:
  # 1. Banco de Dados
  db:
    image: postgres:16-alpine
    container_name: minierp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: MiniErpDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. Interface de Gestão do Banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: minierp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@minierp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  # 3. Back-end (.NET API)
  api:
    container_name: minierp-api
    build:
      context: ./src
      dockerfile: MiniERP.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MiniErpDb;Username=postgres;Password=admin_password
    ports:
      - "5209:8080"
    depends_on:
      - db
    restart: unless-stopped

  # 4. Front-end (Angular via Nginx)
  ui:
    container_name: minierp-ui
    build:
      context: ./src/MiniERP.UI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
    name: minierp-db-data